@startuml


partition "Stack-Developer"  #cccccc {
  (*) --> "Registered Developer"
}

partition "system.name" #aaffaa {
  "Registered Developer" --> "Manage Services"
  "Registered Developer" --> "Manage Application Stacks"
}

@enduml
