@startuml


skinparam packageStyle rect

top to bottom direction

package <size:32>ADC</size>  #dddddd {

  package "<size:24>Software Stack</size>" as SS #ffffaa {
    package "Cloud Connected\nCar Services" { }
    package "Connection Services" { }
    package "Application\nDevelopment Framework" { }
  }
  package "<size:24>Data Center</size>" as DC #ffffff {
      package "Cloud Stack" as CS #lightgreen {
        package "Application Orchestration" { }
        package "Local Service/App Registry" as LSAR { }
        package "Cloud Control" { }
      }
      package "Hardware Stack" as HS #lightblue {
        package "Compute" { }
        package "Storage" { }
        package "Network" { }
      }
  }
  package "Federatated Cloud" as FC #pink {
      package "Global Service/App Registry" as GSAR { }
      package "Global Policy Engine" as GPE { }
      package "Data Exchange" as DE { }
  }
  package "Data Center Geo 1" as DCG1 { }
  package "Data Center Geo 2" as DCG2 { }
  FC --> CS
  FC -> DCG1
  FC --> DCG2
  SS --> FC
}

CS --> HS

@enduml

