@startuml


partition "External Systems" #cccccc {
  (*) ---> "Register to Data Center"
}

partition "ADC" #pink {
  "Register to Data Center" --> "Register External System"
}


partition "External Systems"  {
"Register External System" --> "Registered"
}

partition "ADC" {
  "Registered" -> "Access API Gateway"
  "Registered" -> "Access Data Exchange"
  "Register External System" --> "Data Changed"
}

partition "External Systems" {
  "Data Changed" -> "Notify Changes"
}
@enduml
