@startuml

left to right direction

:External-Systems: as system
:Operations-Manager: as ops

rectangle "ADC" {
    (Register External System) as U1
    (DeRegister External System) as U2
    (Notify of Changes) as U3
    (Manage External Connections) as U4
}

system -> U1
system -> U2
U3 -> system
ops -> U4
U4 --> U2
U4 --> U1

@enduml
