@startuml
|External System|
|#ffaa88|Notify External System|
|External System|
start
|#ffffaa|ADC|
:register external system;
if(connection.type) then (notification)
  #ffaa88:register notification gateway;
  |Notify External System|
  repeat
  :notify of Change;
  :wait for Change;
  repeat while(registered)
  stop
  |ADC|
elseif (connection.type) then (data exchange)
  #lightblue:register data exchange;
  |#lightblue|Data Exchange External System|
  :submit analytics job;
  |ADC|
  #lightblue:run analytics job in Data Centers;
  #lightblue:return results;
  |Data Exchange External System|
  :compile results;
  stop
  |ADC|
elseif (connection.type) then (api gateway)
  #lightgreen:register api gateway;
  |#lightgreen|API External System|
  :access ADC API;
  |ADC|
  #lightgreen:return queried Data;
  |API External System|
  stop
endif

@enduml
