@startuml

package  adc #dddddd {
  storage "Automobile 1" as Car1 #ffffaa
  storage "Automobile 2" as Car2 #ffffaa
  cloud "Private\nGeo 1" as Cloud1 #lightblue {
    node "Connection Services" as CS #ffffff
    node "Cloud Connected Car" as C3 #ffffff
    C3 - CS
    database "Raw" #ffffff
    database "Secondary" #ffffff
    C3 -- Raw
    C3 - Secondary
    Secondary -- CS
  }
  cloud "Private\nGeo 2" as Cloud2 #lightblue {
  }
  cloud "Private\nGeo 3" as Cloud3 #lightblue {
  }
  cloud "Public\nGeo 1" as PG1 #lightgreen {
    node "API Gateway" as AG #ffffff
  }
  CS --> AG
  node "Federated Cloud" as FC #ffffff
  artifact "Alert System\nGeo 1" as AS1 #pink
  artifact "3rd Party Apps" as PA3 #pink

  Car1 --- C3
  AG -- PA3
  CS ---> AS1
  Car2 --- Cloud2

  FC -- Cloud1
  FC -- Cloud2
  FC -- Cloud3
}

@enduml
