@startuml

skinparam packageStyle rect
skinparam interface {
  backgroundColor black
}
top to bottom direction
package "Service Stack"  #dddddd {
  package "Cloud Clonnected Car" #lightblue {
        package "Ingestion Engine" { }
        package "Annotation Engine" #lightgreen { }
        package "Streaming Engine" #lightgreen { }
        package "AI Framework" #lightgreen { }
        package "Analytics" #lightgreen { }
  }
  package "Storage Services" #lightblue {
        package "Raw Storage" { }
        package "Secondary Storage" { }
  }
  package "Connection Services" #lightblue {
      package "Notification Gateway" #lightgreen { }
      package "Application Store" #lightgreen { }
      package "API Gateways" #lightgreen { }
      package "Feedback Gateway" #lightgreen { }
  }
  package "Application Development Framework" #lightblue {
  }
}

package "Alert Systems" { }
package "External Systems" { }
package "Automobile" { }

"Notification Gateway" --> "Alert Systems"
"Automobile" --> "Ingestion Engine"
"Ingestion Engine" --> "Streaming Engine"
"Streaming Engine" --> "Notification Gateway"
"Streaming Engine" --> "Feedback Gateway"
"Feedback Gateway" --> "Automobile"
"Ingestion Engine" --> "Annotation Engine"
"Annotation Engine" --> "Secondary Storage"
"Annotation Engine" --> "Analytics"
"Annotation Engine" --> "AI Framework"
"Secondary Storage" --> "AI Framework"
"AI Framework" --> "Secondary Storage"
"Ingestion Engine" --> "Raw Storage"
"Secondary Storage" --> "API Gateways"
"Analytics" --> "Secondary Storage"
"Analytics" --> "AI Framework"

@enduml

