@startuml
|ApplicationDeveloper|
start
|#ffffaa|system.name|
fork
:Create Application Stack;
:Modify Application Stack;
:Version Application Stack;
fork again
:Create Service Stack;
:Modify Service Stack;
:Version Service Stack;
fork end
|#lightblue|Application Manager|
:Test Application Stack;
:Create an Application;
:Launch an Application in an environment;
:Kill Application and Services;
stop
@enduml
