@startuml
Actor "actorName" as A

box "ADAS" #lightblue
participant CLI as CLI
participant Web as Web
participant "adc" as S
A -> CLI : adc-model-distribute()
CLI -> S : model/distribute()
A -> Web : model/distribute()
Web -> S : model/distribute()
end box

@enduml
