
version: '3'

services:
  # mongo:
  #   image: mongo
  #   expose:
  #        - 27017
  #   ports:
  #        - "27017:27017"
  adc:
    image: adc-web
    expose:
      - 1337
    ports:
      - "1337:1337"
  # uservice-name :
  #  image: adc/uservice-name
  #  deploy:
  #          mode: replicated
  #          replicas: 5
