@startuml

left to right direction

skinparam usecase {
  BackgroudnColor #ffffaa
  BackgroundColor<<Main>> #lightblue
}
actor :User: <<Person>>
actor :SubSystem: <<Person>>


rectangle "Cloud-Stack/Data-Exchange" {
UseCase UC1 <<Main>> as "Use Case1"
UseCase UC2  as "Use Case2"


User --> UC1
UC1 --> UC2
UC2 --> SubSystem
}

@enduml
