@startuml
Actor "Application Developer" as dev

box "Data Center" #lightblue
    participant "adc" as S
    participant "data center" as DC
    participant "DC Ingress" as DCI
    dev -> S : Deploy Application(appDef) : AppID
    S -> DC : createApplication(appDef)
    create "Network" as net #ffaaff
    DC -> net : create(appDef.network)
    create "Application" as app #ffaaff
    DC -> app : create(appDef.app)
    create "Redis" as redis #ffaaff
    app -> redis : create(appDef.service[0])
    create "WebService" as web #ffaaff
    app -> web: create(appDef.service[1])
    create "NodeJS" as node #ffaaff
    app -> node: create(appDef.service[2])
end box
box "Edge" #ffaa88
    participant "Edge Egress" as EE
    create WorkerE as workere #ffaaff
    app -> workere: create(appDef.service[3])
    participant "Edge Ingress" as EI
end box
box "Vehicle" #ffffaa
    participant "Vehicle Egress" as CE
    participant "Sensor Bus" as CI
end box
CI -> CE : gather(data)
CE -> EI : transmit(data)
EI -> workere : transmit(data)
workere -> EE : transmit(data)
EE -> DCI : transmit(data)
DCI -> app : update(data)


@enduml
