@startuml


package "Hybrid Cloud C3" #ffffaa {
  component Application
}
package "In Vehicle" #lightblue {
  component Egress as IVE
}
package "Edge" #lightgreen {
  interface ingress as EVI
  component OverlayNetwork
  Application *-> OverlayNetwork
  component Egress as EVE
  component WebService
  component Redis
  component NodeJS
  component Worker
  Application *..> WebService
  Application *..> Redis
  Application *..> NodeJS
  Application *..> Worker

  WebService -- OverlayNetwork : 8080
  OverlayNetwork -- Redis : 5000
  OverlayNetwork -- NodeJS : 1337
  OverlayNetwork -- Worker : 3000

  EVI --> OverlayNetwork
  OverlayNetwork --> EVE
}

package "Data Center" #ffaa88 {
  interface Ingress as DCI
}

IVE --> EVI
EVE --> DCI

@enduml
