@startuml
Actor "actorName" as A

box "Manage-Data-Exchanges" #lightblue
participant CLI as CLI
participant Web as Web
participant "adc" as S
A -> CLI : adc-global-create()
CLI -> S : global/create()
A -> Web : global/create()
Web -> S : global/create()
end box

@enduml
