@startuml
Actor "actorName" as A

box "Manage-Securitys" #lightblue
participant CLI as CLI
participant Web as Web
participant "adc" as S
A -> CLI : adc-security-detect()
CLI -> S : security/detect()
A -> Web : security/detect()
Web -> S : security/detect()
end box

@enduml
