@startuml
Car1 -> DC1: Send Data
Car1 -> Car1 : Move to another Geo Location
Car1 -> DC2: Send Data
Car1 -> Car1 : Move to another Geo Location
Car1 -> DC3: Send Data

Application -/ "Data Exchange" : Get Data
"Data Exchange" -/ DC1: Get Data
"Data Exchange" -/ DC2: Get Data
"Data Exchange" -/ DC3: Get Data

@enduml
