@startuml


partition "Operations Manager"  #cccccc {
  (*) --> "Registered Admin"
}

partition "ADC" #aaffaa {
  "Registered Admin" --> "Manage Infrastructure"
  "Registered Admin" --> "Manage Applications"
  "Registered Admin" --> "Manage External Connections"
  "Registered Admin" --> "Manage Policies"
  "Registered Admin" --> "Manage Data Coordination"
  "Registered Admin" --> "Manage Services"
}

@enduml
