@startuml

left to right direction

:Operation Manager: as ops

rectangle "ADC" {
    (Manage Infrastructure) as MI
    (Manage Applications) as MA
    (Manage External Connections) as MEC
    (Manage Policies) as MP
    (Manage Data Coordination) as MDC
    (Manage Services) as MS
}

ops --> MI
ops --> MA
ops --> MEC
ops --> MP
ops --> MDC
ops --> MS

@enduml
