@startuml
|Operation Manager|
start
|#lightgreen|system.name|
fork
:Manage Infrastructure;
fork again
:Manage Applications;
fork again
:Manage External Connections;
fork again
:Manage Policies;
fork again
:Manage Data Coordination;
fork again
:Manage Services;
fork end
stop
@enduml
