@startuml

skinparam packageStyle rect

top to bottom direction
package <size:32>ADC</size>  #dddddd {
    package "<size:24>Cloud Connected Car</size>" as CCC #lightblue {
      package "Ingestion Engine" {
      }
      package "Annotation Engine" {
      }
      package "Streaming Engine" {
      }
      package "AI Framework" {
      }
      package "Raw Storage" {
      }
    }

    package "<size:24>Application</size>\n<size:24>Development</size>\n<size:24>Framework</size>" as ADF #lightgreen {
      package "Telematics" {}
      package "Dynamic Mapping" {}
      package "In Vehicle Infomatics" {}
      package "ADAS" {}

    }

    package "<size:24>Connection Services</size>" as CS #ffffaa {
      package "Notification Gateway" {
      }
      package "API Gateways" {
      }
      package "Data Coordinator" {
      }
      package "Feedback Gateway" {
      }
    }
}

package "Alert Systems" { }
package "External Systems" { }
package "Data Centers" { }
package "Automobile" { }

CCC --> ADF
ADF --> CS
left to right direction
CS --> "Alert Systems"
CS --> "External Systems"
CS --> "Data Centers"
"Automobile" --> CCC

@enduml

