@startuml

package "Service-Stack/Connected-Car-Cloud/Annotation-Engine" {
    interface "Service-Stack/Connected-Car-Cloud/Annotation-Engine" {

    }
    CLI ()-- "Service-Stack/Connected-Car-Cloud/Annotation-Engine"
    REST ()-- "Service-Stack/Connected-Car-Cloud/Annotation-Engine"
    Web ()-- "Service-Stack/Connected-Car-Cloud/Annotation-Engine"

}


@enduml
