@startuml
Actor "actorName" as A

box "In-Vehicle-Informatics" #lightblue
participant CLI as CLI
participant Web as Web
participant "adc" as S
A -> CLI : adc-content-distribute()
CLI -> S : content/distribute()
A -> Web : content/distribute()
Web -> S : content/distribute()
end box

@enduml
